import Link from 'next/link'
import { notFound } from 'next/navigation'
import { ArrowLeft, ArrowUpRight, Bath, BedDouble, Check, Heart, MapPin, Maximize, MessageCircle } from 'lucide-react'
import { getProperty, properties, whatsappLink } from '@/lib/properties'

export function generateStaticParams() { return properties.map((property) => ({ id: property.id })) }

export default async function ObjectPage({ params }: { params: Promise<{ id: string }> }) {
  const { id } = await params
  const property = getProperty(id)
  if (!property) notFound()
  return <main><header className="site-header"><Link href="/" className="brand"><span className="brand-mark">GB</span><span>García Baillos<small>Propiedades</small></span></Link><Link href="/catalog" className="header-contact"><ArrowLeft /> Volver al catálogo</Link></header><section className="object-page section-shell"><Link href="/catalog" className="back-link"><ArrowLeft /> Todas las propiedades</Link><div className="object-gallery"><img src={property.images[0]} alt={property.title} /><div className="gallery-side">{property.images.slice(1, 3).map((image) => <img src={image} alt="Interior del inmueble" key={image} />)}</div></div><div className="object-layout"><div><div className="section-kicker">{property.operation} · {property.neighborhood}</div><h1>{property.title}</h1><p className="object-address"><MapPin /> {property.address}, Buenos Aires</p><div className="object-price">{property.price}</div><div className="object-meta-large"><span><BedDouble /> {property.rooms} ambientes</span><span><Bath /> {property.baths} baños</span><span><Maximize /> {property.area} m²</span></div><div className="object-description"><h2>Sobre este lugar</h2><p>{property.description}</p><p>Diseñado para que la luz, el aire y la vida cotidiana encuentren su propio ritmo. Consultanos para conocer todos los detalles y coordinar una visita.</p></div></div><aside className="contact-card"><div className="contact-card-top"><span>¿Te interesa?</span><Heart /></div><h2>Hablemos de<br /><em>este lugar.</em></h2><p>Te respondemos personalmente, sin vueltas.</p><Link href={whatsappLink(property)} target="_blank" className="button button-blue"><MessageCircle /> Consultar por WhatsApp <ArrowUpRight /></Link><a href="tel:+5491155550182" className="phone-link">+54 9 11 5555 0182</a></aside></div><div className="object-details"><h2>Detalles</h2><div>{['Luminoso y silencioso','Balcón / terraza','Cocina equipada','Apto mascotas'].map((detail) => <span key={detail}><Check /> {detail}</span>)}</div></div><div className="map-block"><div><div className="section-kicker">El barrio</div><h2>Todo cerca,<br /><em>todo posible.</em></h2><p><MapPin /> {property.neighborhood}, Buenos Aires</p></div><div className="map-placeholder"><div className="map-pin"><MapPin /></div><span>Mapa de {property.neighborhood}</span></div></div></section><footer className="contact-section object-footer"><div className="footer-row"><span>© 2024 García Baillos Propiedades</span><span>Hablemos · +54 9 11 5555 0182</span></div></footer></main>
}
